### ISSUE TITLE
group to continents?

### ISSUE THREAD

**Issue by eFrane** [eFrane/admin0#3]
grouping the country files to continents as in https://github.com/juliuste/admin0-continents might be a good idea, additionally, the file names should probably reflect ISO 3166-1 ALPHA 1 Country codes, e.g. countries/Germany.geojson would become europe/de.geojson

**Comment by derhuerst** [comment]
I like that the files wouldn't contain spaces & special chars anymore. Also, with any country codes, naming conflicts because of political changes can be easily avoided.
